# Generated by Django 3.0.5 on 2020-04-28 17:43

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_account_link', models.TextField()),
                ('verified', models.CharField(blank=True, default='False', max_length=10)),
                ('profile_picture', models.URLField(max_length=256, null=True)),
                ('users_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('facebook', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('instagram', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('tiktok', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('youtube', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('snapchat', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Professional', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'professional',
            },
        ),
        migrations.CreateModel(
            name='IndividualUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.URLField(max_length=256, null=True)),
                ('verified', models.TextField(default='False')),
                ('users_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('facebook', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('instagram', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('tiktok', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('youtube', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('snapchat', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Individual', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'individual',
            },
        ),
        migrations.CreateModel(
            name='CorporateUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('profile_picture', models.URLField(max_length=256, null=True)),
                ('corporate_link', models.CharField(max_length=200)),
                ('verified', models.CharField(blank=True, default='False', max_length=10)),
                ('users_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('facebook', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('instagram', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('tiktok', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('youtube', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('snapchat', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Corporate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corporate',
            },
        ),
    ]
