# Generated by Django 3.0.5 on 2020-04-28 17:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateuser',
            name='facebook',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='instagram',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='snapchat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='tiktok',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='youtube',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='facebook',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='instagram',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='snapchat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='tiktok',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='youtube',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='facebook',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='instagram',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='snapchat',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='tiktok',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='youtube',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, null=True), size=None),
        ),
    ]
