# Generated by Django 3.0.5 on 2020-04-28 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200428_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateuser',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='instagram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='snapchat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='tiktok',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='youtube',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='instagram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='snapchat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='tiktok',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='youtube',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='facebook',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='instagram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='snapchat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='tiktok',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='youtube',
            field=models.TextField(blank=True, null=True),
        ),
    ]
