# Generated by Django 3.0.5 on 2020-05-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200428_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateuser',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualuser',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionaluser',
            name='twitter',
            field=models.TextField(blank=True, null=True),
        ),
    ]
