# Generated by Django 3.0.5 on 2020-05-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200511_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateuser',
            name='facebook',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='instagram',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='snapchat',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='tiktok',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='twitter',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='corporateuser',
            name='youtube',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='facebook',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='instagram',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='snapchat',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='tiktok',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='twitter',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='youtube',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='facebook',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='instagram',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='snapchat',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='tiktok',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='twitter',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AlterField(
            model_name='professionaluser',
            name='youtube',
            field=models.TextField(blank=True, default='{}'),
        ),
    ]
