# Generated by Django 3.0.5 on 2020-05-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200511_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualuser',
            name='facebook',
            field=models.TextField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='instagram',
            field=models.TextField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='snapchat',
            field=models.TextField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='tiktok',
            field=models.TextField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='twitter',
            field=models.TextField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='youtube',
            field=models.TextField(blank=True, default={}, null=True),
        ),
    ]
