# Generated by Django 3.0.5 on 2020-05-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200511_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualuser',
            name='facebook',
            field=models.TextField(blank=True, default={}),
        ),
    ]
