# Generated by Django 3.0.5 on 2020-05-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200511_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaluser',
            name='facebook',
            field=models.TextField(default='------'),
        ),
    ]
